from _typeshed import Incomplete
from langgraph.channels.base import BaseChannel, Value
from typing import Callable, Generic, Sequence
from typing_extensions import Self

class BinaryOperatorAggregate(BaseChannel[Value, Value, Value], Generic[Value]):
    operator: Incomplete
    value: Incomplete
    def __init__(self, typ: type[Value], operator: Callable[[Value, Value], Value]) -> None: ...
    def __eq__(self, value: object) -> bool: ...
    @property
    def ValueType(self) -> type[Value]: ...
    @property
    def UpdateType(self) -> type[Value]: ...
    def from_checkpoint(self, checkpoint: Value | None) -> Self: ...
    def update(self, values: Sequence[Value]) -> bool: ...
    def get(self) -> Value: ...
