from langgraph.channels.base import BaseChannel, Value
from typing import Any, Generic, NamedTuple, Sequence
from typing_extensions import Self

class WaitForNames(NamedTuple):
    names: set[Any]

class DynamicBarrierValue(BaseChannel[Value, Value | WaitForNames, set[Value]], Generic[Value]):
    names: set[Value] | None
    seen: set[Value]
    def __init__(self, typ: type[Value]) -> None: ...
    def __eq__(self, value: object) -> bool: ...
    @property
    def ValueType(self) -> type[Value]: ...
    @property
    def UpdateType(self) -> type[Value]: ...
    def checkpoint(self) -> tuple[set[Value] | None, set[Value]]: ...
    def from_checkpoint(self, checkpoint: tuple[set[Value] | None, set[Value]] | None) -> Self: ...
    def update(self, values: Sequence[Value | WaitForNames]) -> bool: ...
    def get(self) -> Value: ...
    def consume(self) -> bool: ...
