from typing import Any, Generator

def get_field_default(name: str, type_: Any, schema: type[Any]) -> Any: ...
def get_enhanced_type_hints(type: type[Any]) -> Generator[tuple[str, Any, Any, str | None], None, None]: ...
