"""
Version information for LangGraph.

This file is automatically generated by setuptools-scm at build time.
"""

# This will be replaced by setuptools-scm during the build process
__version__ = "0.0.0"
