from langchain_core.runnables import RunnableConfig as RunnableConfig
from langgraph.store.base import BaseStore as BaseStore
from langgraph.types import StreamWriter as StreamWriter

def get_config() -> RunnableConfig: ...
def get_store() -> BaseStore: ...
def get_stream_writer() -> StreamWriter: ...
