from typing import Any, Callable, TypeVar

class LangGraphDeprecationWarning(DeprecationWarning): ...
F = TypeVar('F', bound=Callable[..., Any])
C = TypeVar('C', bound=type[Any])

def deprecated(since: str, alternative: str, *, removal: str = '', example: str = '') -> Callable[[F], F]: ...
def deprecated_parameter(arg_name: str, since: str, alternative: str, *, removal: str) -> Callable[[F], F]: ...
