.PHONY: run_w_override

run:
	uv run langgraph up --watch --no-pull

run_faux:
	cd graphs && uv run langgraph up --no-pull

run_graphs_reqs_a:
	cd graphs_reqs_a && uv run langgraph up --no-pull

run_graphs_reqs_b:
	cd graphs_reqs_b && uv run langgraph up --no-pull
