.PHONY: run_w_override

run:
	poetry run langgraph up --watch --no-pull

run_faux:
	cd graphs && poetry run langgraph up --no-pull

run_graphs_reqs_a:
	cd graphs_reqs_a && poetry run langgraph up --no-pull

run_graphs_reqs_b:
	cd graphs_reqs_b && poetry run langgraph up --no-pull
